"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { useReducer, useEffect } from "react";
import { IRestaurant } from "./models/IRestaurant";
import { RestaurantReducer } from "./reducers/RestaurantReducer";
import { createRestaurant } from "./services/RestaurantService";
import { RestaurantContext } from "./contexts/RestaurantContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  metadata,
}: {
  children: React.ReactNode;
  metadata: Metadata;
}) {
  const [restaurant, dispatch] = useReducer(
    RestaurantReducer,
    {} as IRestaurant
  );
  // const [restaurant, setRestaurant] = useState<ICreateRestaurant | null>(null)

  useEffect(() => {
    createRestaurant()
      .then((data) => {
        dispatch({ type: "SET_RESTAURANT", payload: data });
      })
      .catch((error) => {
        console.error("Error", error);
      });
  }, []);
  console.log(restaurant);

  return (
    <html lang="en">
      <body className={inter.className}>
        <RestaurantContext.Provider value={restaurant}>
          <Header />
          {children}
          <Footer></Footer>
        </RestaurantContext.Provider>
      </body>
    </html>
  );
}
